<?xml version="1.0" encoding="UTF-8" ?>
<!-- 엘리먼트 타입 - 여러 개 중에 한 개의 엘리먼트 선택
    - <!ELEMENT 이름 (태그1 | 태그2 | 태그3)>
-->

<!DOCTYPE books [
<!ELEMENT books (book)*>
<!ELEMENT book (title,author+,press,page,description?,photo*,(cd|tape|usb)?)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT press (#PCDATA)>
<!ELEMENT page (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT photo (#PCDATA)>
<!ELEMENT cd EMPTY>
<!ELEMENT tape EMPTY>
<!ELEMENT usb EMPTY>
]>


<books>
    <book>
        <title>aaa</title>
        <author>bbb</author>
        <press>ccc</press>
        <page>300</page>
    </book>
    <book>
        <title>aaa</title>
        <author>bbb</author>
        <press>ccc</press>
        <page>300</page>
        <cd/>
    </book>
    <book>
        <title>aaa</title>
        <author>bbb</author>
        <press>ccc</press>
        <page>300</page>
        <tape/>
    </book>
    <book>
        <title>aaa</title>
        <author>bbb</author>
        <press>ccc</press>
        <page>300</page>
        <usb/>
    </book>
    <book>
        <title>aaa</title>
        <author>bbb</author>
        <press>ccc</press>
        <page>300</page>
        <usb/>
        <cd/>
    </book>
</books>
