<?xml version="1.0" encoding="UTF-8" ?>
<!-- 엘리먼트 타입 - 여러 개의 자식 태그
    - <!ELEMENT 이름 (자식태그명, 자식태그명,...)>
-->

<!DOCTYPE books [
<!ELEMENT books (book)*>
<!ELEMENT book (title,author,press)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT press (#PCDATA)>
]>


<books>
    <book>
        <title>aaa</title>
        <author>bbb</author>
        <press>ccc</press>    
    </book>
    <book>
        <title>aaa</title>
        <author>bbb</author>
        <press>ccc</press>    
    </book>
</books>
